name: GraphQL
on:
  workflow_dispatch:
    inputs:
      org-name:
        description: 'Enter the Organization Name'
        required: true
      repo-name:
        description: 'Enter the repository name'
        required: true
    
jobs:
  graph-ql:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "QUERY=$(cat <<EOF
          query {
            repository(owner: \${{ inputs.org-name }}, name: \${{ inputs.repo-name }}) {
              name
              description
              homepageUrl
              hasIssuesEnabled
              hasWikiEnabled
              hasProjectsEnabled
              isArchived
              isTemplate
              licenseInfo {
                name
                spdxId
              }
              defaultBranchRef {
                name
              }
            }
          }
          EOF
          )" >> $GITHUB_ENV
          
      - name: Send GraphQL query
        run: |
          curl -X POST \
            -H "Authorization: bearer ${{ secrets.MY_SECRETS }}" \
            -H "Content-Type: application/json" \
            -d "$QUERY" \
            https://api.github.com/graphql